"""SQLAlchemy declarative base.

All ORM models inherit from `Base`. A naming convention is applied so that
every constraint and index Alembic generates has a predictable, stable
name (`ix_...`, `uq_...`, `ck_...`, `fk_...`, `pk_...`). Without this,
autogenerated migrations use database-assigned names that differ between
environments and make future migrations (e.g. dropping a constraint)
error-prone.
"""

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)
